Google SSO fixes + limiting to hosted domain (#412)
* Make SSO work for Google Apps For Work

When trying to make SSO work for Google Apps For Work, I faced the
following error message:
  Error: invalid_request
  Invalid response_type: authorization_code
  Learn more
  That’s all we know.

The only way I made it work was to change a few parameters:
responseType, scope.
I also hade to modify the url_for() call as my securitymonkey
install is behind a SSL proxy.
There are certainly better ways to make it work but I'm not
a Flask expert and could not find a way to have it create
the proper urls.

* Limit Google SSO to specific domain

In order to limit Google SSO to specific Hosted Domains, we
introduce a new configuration setting (optional):
 GOOGLE_HOSTED_DOMAIN

If GOOGLE_HOSTED_DOMAIN is not set, nothing happens.
If GOOGLE_HOSTED_DOMAIN is set in the config file, its value
is used as the parameter 'hd' in calls to Google SSO authentication
request (to GOOGLE_AUTH_ENDPOINT), and the returned ID token will
also be verified to conform to this Hosted Domain.

That way you can limit login only to users of your organisation.

* Fixing a copy/paste typo